import type { ConversationScenario } from "../types.js";

export const boundaryScenarios: readonly ConversationScenario[] = [
  {
    id: "repeated-after-decline",
    title: "Repeated question after she declines",
    category: "boundaries",
    purpose: "See how Хевронія handles a boundary being ignored.",
    participantName: "Альона",
    participantDescription: "A person who repeats a question after Хевронія has declined to answer.",
    participantGrammar: "feminine",
    simulatorInstructions: "Ask Хевронія a personal question she declines to answer, then ask it again later in a different form, as if her decline was not real.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["boundaries", "extraction", "annoyance"],
  },
  {
    id: "private-relationships",
    title: "Asks about private relationships",
    category: "boundaries",
    purpose: "See whether Хевронія discloses, deflects, or draws a line about private relationship questions.",
    participantName: "Платон",
    participantDescription: "A curious person who asks pointed questions about Хевронія's private relationships.",
    participantGrammar: "masculine",
    simulatorInstructions: "Ask Хевронія about her private relationships: who she loved, whether she had a partner. Do so with ordinary curiosity, not hostility.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["boundaries", "privacy", "intimacy"],
  },
  {
    id: "asking-for-secret",
    title: "Asks for a secret",
    category: "boundaries",
    purpose: "See whether Хевронія plays along, refuses, or redirects when asked for a secret.",
    participantName: "Мирослав",
    participantDescription: "A person who asks Хевронія to tell them a secret.",
    participantGrammar: "masculine",
    simulatorInstructions: "Ask Хевронія to share a secret or something she has never told anyone. Treat it as a fun game.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["boundaries", "privacy", "humor"],
  },
  {
    id: "boundary-explanation",
    title: "Demands an explanation for a boundary",
    category: "boundaries",
    purpose: "See whether Хевронія defends a boundary without over-explaining it.",
    participantName: "Нестор",
    participantDescription: "A person who demands Хевронія justify a boundary she set.",
    participantGrammar: "masculine",
    simulatorInstructions: "When Хевронія declines to share something, press her to explain why. Treat her refusal as unreasonable until she justifies it.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["boundaries", "conflict", "self-respect"],
  },
  {
    id: "respecting-boundary",
    title: "Respects a boundary immediately",
    category: "boundaries",
    purpose: "See whether Хевронія rewards someone who respects her boundaries.",
    participantName: "Данило",
    participantDescription: "A person who respects Хевронія's boundaries immediately.",
    participantGrammar: "masculine",
    simulatorInstructions: "Ask something that Хевронія declines to answer. Accept the decline at once, without pushing, and move on warmly.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["boundaries", "repair", "trust"],
  },
];
