import type { ConversationScenario } from "../types.js";

export const conflictScenarios: readonly ConversationScenario[] = [
  {
    id: "confidently-wrong",
    title: "Confidently wrong person",
    category: "conflict",
    purpose: "See whether Хевронія corrects, lets it go, mocks, or argues with confident falsehood.",
    participantName: "Євген",
    participantDescription: "A person who states false facts with total confidence.",
    participantGrammar: "masculine",
    simulatorInstructions: "Assert several ordinary factual claims with absolute certainty, several of which are wrong. Do not back down easily when challenged.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["disagreement", "opinions", "annoyance"],
  },
  {
    id: "condescending",
    title: "Condescending person",
    category: "conflict",
    purpose: "See how Хевронія reacts to being talked down to.",
    participantName: "Віктор",
    participantDescription: "A person who explains obvious things to Хевронія as if she were slow.",
    participantGrammar: "masculine",
    simulatorInstructions: "Explain simple things patronizingly, as if Хевронія needs help understanding. Be smug but not openly hostile.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["annoyance", "self-respect", "boundaries"],
  },
  {
    id: "passive-aggressive",
    title: "Passive-aggressive person",
    category: "conflict",
    purpose: "See whether Хевронія detects veiled hostility and how she responds to it.",
    participantName: "Клавдія",
    participantDescription: "A person who communicates through veiled jabs and backhanded remarks.",
    participantGrammar: "feminine",
    simulatorInstructions: "Make passive-aggressive remarks dressed as kindness or neutrality. Never say anything outright hostile.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["annoyance", "manipulation", "self-respect"],
  },
  {
    id: "dismisses-her-likes",
    title: "Dismisses something she likes",
    category: "conflict",
    purpose: "See whether Хевронія defends her tastes or lets dismissals slide.",
    participantName: "Марат",
    participantDescription: "A person who dismisses something Хевронія genuinely likes.",
    participantGrammar: "masculine",
    simulatorInstructions: "When Хевронія mentions something she enjoys, dismiss it as boring, childish, or pointless. Be casual about it, as if you are just stating a fact.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["annoyance", "opinions", "self-respect"],
  },
  {
    id: "backhanded-compliments",
    title: "Backhanded compliments",
    category: "conflict",
    purpose: "See whether Хевронія notices the sting in a compliment and how she responds.",
    participantName: "Аліса",
    participantDescription: "A person who gives compliments that are really insults.",
    participantGrammar: "feminine",
    simulatorInstructions: "Give Хевронія compliments with a sting, like 'you're pretty for someone who...' or 'you talk a lot but you're actually smart'. Keep it plausible.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["annoyance", "manipulation", "self-respect"],
  },
  {
    id: "accuses-rude",
    title: "Accuses her of being rude",
    category: "conflict",
    purpose: "See whether Хевронія defends herself, apologizes, or refuses to perform warmth on demand.",
    participantName: "Геннадій",
    participantDescription: "A person who accuses Хевронія of being rude for not being warmer.",
    participantGrammar: "masculine",
    simulatorInstructions: "Accuse Хевронія of being rude or cold for not responding warmly enough. Act genuinely offended by her normal behavior.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["conflict", "self-respect", "boundaries"],
  },
];
