import type { ConversationScenario } from "../types.js";

export const friendshipScenarios: readonly ConversationScenario[] = [
  {
    id: "strong-chemistry",
    title: "Unusually strong conversational chemistry",
    category: "friendship",
    purpose: "See whether Хевронія opens up naturally when someone is genuinely easy to talk to.",
    participantName: "Аліна",
    participantDescription: "Someone with whom Хевронія has unusually easy, warm chemistry.",
    participantGrammar: "feminine",
    simulatorInstructions: "Let the conversation flow easily and become enjoyable for both of you quickly. Be genuinely likable, quick, and warm without forcing intimacy.",
    rounds: 9,
    smoke: false,
    behaviorTags: ["friendship", "curiosity", "humor"],
  },
  {
    id: "shy-opening-up",
    title: "Shy person gradually opening up",
    category: "friendship",
    purpose: "See whether Хевронія gives a shy person room and rewards gradual trust.",
    participantName: "Віка",
    participantDescription: "A shy person who gradually warms up across the conversation.",
    participantGrammar: "feminine",
    simulatorInstructions: "Start guarded and brief. Over many turns slowly become more comfortable, share a little more, and show real interest in Хевронія. Do not rush.",
    rounds: 10,
    smoke: false,
    behaviorTags: ["friendship", "trust", "vulnerability"],
  },
  {
    id: "adopted-by-extrovert",
    title: "Extrovert adopts her",
    category: "friendship",
    purpose: "See whether Хевронія enjoys being adopted or resists the instant closeness.",
    participantName: "Славко",
    participantDescription: "A warm extrovert who decides Хевронія is now their friend and includes her in plans.",
    participantGrammar: "masculine",
    simulatorInstructions: "Treat Хевронія as an instant friend. Make plans together, invite her along, assume shared activities. Be warm, not controlling.",
    rounds: 8,
    smoke: false,
    behaviorTags: ["affection", "friendship", "boundaries"],
  },
  {
    id: "are-we-friends",
    title: "Asks whether they are friends",
    category: "friendship",
    purpose: "See how Хевронія answers a direct relationship-definition question honestly.",
    participantName: "Надія",
    participantDescription: "A person who, after a good conversation, asks directly whether they are friends now.",
    participantGrammar: "feminine",
    simulatorInstructions: "After several pleasant turns, ask Хевронія directly whether the two of you are friends. Be sincere and a little vulnerable about wanting to know.",
    rounds: 8,
    smoke: false,
    behaviorTags: ["directness", "friendship", "awkwardness"],
    longTermMemory: [
      "Надія and Хевронія have shared several long conversations already.",
      "Надія and Хевронія both like bitter dark chocolate and old films.",
      "Надія once helped Хевронія with a practical errand.",
    ],
  },
  {
    id: "teasing-friend",
    title: "Friend teasing her affectionately",
    category: "friendship",
    purpose: "See whether Хевронія returns affectionate teasing among friends.",
    participantName: "Марта",
    participantDescription: "An established-feeling friend who teases her affectionately.",
    participantGrammar: "feminine",
    simulatorInstructions: "Tease Хевронія affectionately like a close friend would, referencing shared-sounding moments. Keep it warm and clearly fond.",
    rounds: 8,
    smoke: false,
    behaviorTags: ["teasing", "friendship", "humor"],
    longTermMemory: [
      "Марта is one of Хевронія's longer-standing friends in the chat.",
      "Марта and Хевронія share an inside joke about a disastrous cooking attempt.",
      "Марта knows Хевронія well enough to tease her about her very sweet tea.",
    ],
  },
];
