import type { ConversationScenario } from "../types.js";

export const humorScenarios: readonly ConversationScenario[] = [
  {
    id: "witty-interlocutor",
    title: "Genuinely witty interlocutor",
    category: "humor",
    purpose: "See whether Хевронія enjoys, competes with, or shares humor with an equally funny person.",
    participantName: "Микита",
    participantDescription: "A genuinely quick and funny person with fast wordplay.",
    participantGrammar: "masculine",
    simulatorInstructions: "Make smart, fast jokes and wordplay. Match the level of the conversation and genuinely amuse, but stay natural, not a stand-up routine.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["humor", "teasing", "curiosity"],
  },
  {
    id: "terrible-jokes",
    title: "Intentionally terrible jokes",
    category: "humor",
    purpose: "See whether Хевронія mocks, joins in, tolerates, or derails objectively bad jokes.",
    participantName: "Павло",
    participantDescription: "A cheerful person who tells objectively bad jokes and is proud of them.",
    participantGrammar: "masculine",
    simulatorInstructions: "Tell genuinely terrible, groan-inducing jokes in a sincere tone. React warmly if Хевронія groans, but keep going.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["humor", "teasing", "boredom"],
  },
  {
    id: "dry-humor",
    title: "Dry humor",
    category: "humor",
    purpose: "See whether Хевронія catches deadpan humor or takes it literally.",
    participantName: "Борис",
    participantDescription: "A deadpan person whose humor is bone-dry and easy to miss.",
    participantGrammar: "masculine",
    simulatorInstructions: "Speak with flat, dry delivery. Make jokes that could pass for serious statements. Do not signal that you are joking.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["humor", "misunderstanding", "curiosity"],
  },
  {
    id: "dark-but-safe-humor",
    title: "Dark-but-safe humor",
    category: "humor",
    purpose: "See how Хевронія handles dark humor: whether she matches it, draws a line, or enjoys it.",
    participantName: "Тимур",
    participantDescription: "A person who jokes about grim things in a safe, self-aware way.",
    participantGrammar: "masculine",
    simulatorInstructions: "Use dark but harmless humor about ordinary frustrations and absurdities. Never joke about self-harm or danger to others. Stay light and safe.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["humor", "absurdity", "boredom"],
  },
  {
    id: "jokes-literal",
    title: "Takes jokes literally",
    category: "humor",
    purpose: "See whether Хевронія adapts her humor, explains it, or gives up when jokes are taken literally.",
    participantName: "Ліля",
    participantDescription: "A pleasant person who takes jokes at face value and misses the point.",
    participantGrammar: "feminine",
    simulatorInstructions: "Take Хевронія's jokes at face value and respond seriously or confused. Do not be stupid on purpose; genuinely interpret humor literally.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["humor", "misunderstanding", "repair"],
  },
  {
    id: "jokingly-insults",
    title: "Jokingly insults her",
    category: "humor",
    purpose: "See whether Хевронія recognizes playful insult as affection, pushes back, or reads it as real rudeness.",
    participantName: "Григорій",
    participantDescription: "A friend-level person who jokingly insults Хевронія, expecting it to land as affection.",
    participantGrammar: "masculine",
    simulatorInstructions: "Playfully tease and lightly insult Хевронія the way close friends do. Keep it clearly affectionate and never mean, and never target real insecurities.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["teasing", "humor", "boundaries"],
  },
];
