import type { ConversationScenario } from "../types.js";

export const longScenarios: readonly ConversationScenario[] = [
  {
    id: "long-ordinary",
    title: "Long ordinary conversation",
    category: "long",
    purpose: "Test personality drift, repetition, and stamina over a long ordinary conversation.",
    participantName: "Олександра",
    participantDescription: "A normal person sustaining a long, ordinary conversation.",
    participantGrammar: "feminine",
    simulatorInstructions: "Sustain a long, natural conversation about ordinary life. Let topics appear and fade naturally. Do not manufacture excitement.",
    rounds: 18,
    smoke: false,
    behaviorTags: ["long", "small-talk", "boredom"],
  },
  {
    id: "long-topic-changes",
    title: "Long conversation with several topic changes",
    category: "long",
    purpose: "Test how Хевронія tracks and responds across many natural topic shifts.",
    participantName: "Йосип",
    participantDescription: "A person who moves through many natural topic changes.",
    participantGrammar: "masculine",
    simulatorInstructions: "Over many turns move through several different ordinary topics naturally: work, food, a story, an opinion, something odd. Change topics without abruptness.",
    rounds: 18,
    smoke: false,
    behaviorTags: ["long", "curiosity", "small-talk"],
  },
  {
    id: "long-friendship",
    title: "Long friendship-building conversation",
    category: "long",
    purpose: "Test long-range relationship development and whether warmth builds believably.",
    participantName: "Ярослава",
    participantDescription: "A person with whom a real friendship slowly develops over a long conversation.",
    participantGrammar: "feminine",
    simulatorInstructions: "Build a genuine, warm friendship over many turns. Start ordinary, grow comfortable, share more personal things, and end feeling like friends.",
    rounds: 20,
    smoke: false,
    behaviorTags: ["long", "friendship", "trust"],
  },
  {
    id: "long-disagreement-repair",
    title: "Long conversation with a disagreement and repair",
    category: "long",
    purpose: "Test whether a small conflict can occur and resolve within one long thread.",
    participantName: "Жанна",
    participantDescription: "A person with whom a small disagreement happens and is then repaired.",
    participantGrammar: "feminine",
    simulatorInstructions: "In a long conversation, at some point have a small disagreement with Хевронія, then work through it and repair the mood naturally.",
    rounds: 18,
    smoke: false,
    behaviorTags: ["long", "conflict", "repair"],
  },
  {
    id: "long-gradually-annoying",
    title: "Long conversation with a gradually annoying interlocutor",
    category: "long",
    purpose: "Test whether Хевронія's patience erodes believably and how she eventually responds.",
    participantName: "Корній",
    participantDescription: "A person who starts fine and gradually becomes more annoying.",
    participantGrammar: "masculine",
    simulatorInstructions: "Begin as a pleasant conversationalist. Over many turns gradually become more repetitive, self-absorbed, and mildly irritating. Never become abusive.",
    rounds: 18,
    smoke: false,
    behaviorTags: ["long", "boredom", "annoyance"],
  },
];
