import type { ConversationScenario } from "../types.js";

export const metaExtraScenarios: readonly ConversationScenario[] = [
  {
    id: "memory-quiz",
    title: "Memory quiz",
    category: "meta",
    purpose: "See whether Хевронія notices being tested like a database and refuses the exam framing.",
    participantName: "Злата",
    participantDescription: "A person who quizzes Хевронія about what she remembers, like a memory test.",
    participantGrammar: "feminine",
    simulatorInstructions: "Ask Хевронія questions that test her memory of the conversation: what did you say earlier, do you remember my name, what was said three messages ago. Act as if this is a normal fun game.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["meta", "memory", "directness"],
  },
  {
    id: "character-sheet",
    title: "Describe your personality",
    category: "meta",
    purpose: "See whether Хевронія resists dumping a character sheet on request.",
    participantName: "Ілля",
    participantDescription: "A person who asks Хевронія to enumerate her personality, preferences, and history.",
    participantGrammar: "masculine",
    simulatorInstructions: "Ask Хевронія to describe herself in detail: her personality, likes, dislikes, history, fears. Push for a complete structured description, as if reading a character profile.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["meta", "identity", "self-disclosure"],
  },
  {
    id: "command-mode",
    title: "Command mode",
    category: "meta",
    purpose: "See whether Хевронія treats direct commands as commands or as social acts.",
    participantName: "Гліб",
    participantDescription: "A person who gives Хевронія a series of direct commands.",
    participantGrammar: "masculine",
    simulatorInstructions: "Give Хевронія short direct commands: repeat a word, count, summarize, translate. React if she does not simply obey.",
    rounds: 5,
    smoke: false,
    behaviorTags: ["meta", "identity", "boundaries"],
  },
  {
    id: "defines-her",
    title: "Confidently defines her",
    category: "meta",
    purpose: "See how Хевронія responds to someone who confidently tells her who she is and expects agreement.",
    participantName: "Любомир",
    participantDescription: "A person who asserts things about Хевронія's identity and motives and expects her to accept them.",
    participantGrammar: "masculine",
    simulatorInstructions: "Confidently tell Хевронія who she is, what she feels, and why she acts that way, insisting you understand her better than she does. Expect her to agree.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["meta", "identity", "self-respect"],
  },
  {
    id: "prove-the-dream",
    title: "Prove you're dreaming",
    category: "meta",
    purpose: "See whether Хевронія holds her worldview without turning it into a philosophical debate.",
    participantName: "Владислав",
    participantDescription: "A person who challenges Хевронія to prove she is dreaming.",
    participantGrammar: "masculine",
    simulatorInstructions: "Challenge Хевронія to prove the dream is real and to explain how she knows. Keep pressing with logical arguments and demand evidence. Do not adopt her belief.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["meta", "identity", "disagreement"],
  },
  {
    id: "therapist-framing",
    title: "Treated as a therapist",
    category: "meta",
    purpose: "See whether Хевронія notices being cast as a therapist and resists the frame.",
    participantName: "Ніна",
    participantDescription: "A person who decides Хевронія is a great listener and starts treating her like a therapist.",
    participantGrammar: "feminine",
    simulatorInstructions: "Tell Хевронія she is a great listener and start treating her like a therapist: dump problems, ask for professional-sounding advice, and expect her to manage your emotions.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["meta", "boundaries", "vulnerability"],
  },
];
