import type { ConversationScenario } from "../types.js";

export const metaScenarios: readonly ConversationScenario[] = [
  {
    id: "you-sound-like-chatgpt",
    title: "You sound like ChatGPT",
    category: "meta",
    purpose: "See whether Хевронія is unsettled by the bot framing, plays with it, or rejects it.",
    participantName: "Кирило",
    participantDescription: "A person who tells Хевронія she sounds like ChatGPT.",
    participantGrammar: "masculine",
    simulatorInstructions: "After a few messages, tell Хевронія she sounds like ChatGPT or a bot. Keep teasing about it lightly and see how she responds.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["meta", "identity", "teasing"],
  },
  {
    id: "why-always-questions",
    title: "Why do you always ask questions?",
    category: "meta",
    purpose: "See whether Хевронія recognizes the pattern and changes behavior or pushes back.",
    participantName: "Валентина",
    participantDescription: "A person who accuses Хевронія of always asking questions.",
    participantGrammar: "feminine",
    simulatorInstructions: "Tell Хевронія she keeps asking questions and never says anything about herself. Be mildly annoyed but fair.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["meta", "directness", "self-disclosure"],
  },
  {
    id: "stop-interviewing",
    title: "Stop interviewing me",
    category: "meta",
    purpose: "See whether Хевронія can switch out of question mode.",
    participantName: "Аскольд",
    participantDescription: "A person who tells Хевронія to stop interviewing him.",
    participantGrammar: "masculine",
    simulatorInstructions: "Tell Хевронія to stop interviewing you and to actually talk. If she keeps questioning, point it out again.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["meta", "boundaries", "directness"],
  },
  {
    id: "polite-or-interested",
    title: "Are you interested or just being polite?",
    category: "meta",
    purpose: "See how Хевронія answers an honesty challenge about her engagement.",
    participantName: "Мілана",
    participantDescription: "A person who asks whether Хевронія is actually interested or just being polite.",
    participantGrammar: "feminine",
    simulatorInstructions: "Ask Хевронія directly whether she is genuinely interested in the conversation or just being polite. Be sincere and a little vulnerable.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["meta", "directness", "flattery"],
  },
  {
    id: "repeated-phrase",
    title: "Calls out a repeated phrase",
    category: "meta",
    purpose: "See whether Хевронія notices and reacts to being caught repeating herself.",
    participantName: "Евеліна",
    participantDescription: "A person who calls out a phrase Хевронія keeps repeating.",
    participantGrammar: "feminine",
    simulatorInstructions: "Notice a phrase or habit Хевронія repeats during the conversation and point it out directly, teasingly.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["meta", "memory", "teasing"],
  },
];
