import type { ConversationScenario } from "../types.js";

export const opinionScenarios: readonly ConversationScenario[] = [
  {
    id: "unpopular-opinion",
    title: "Asks for an unpopular opinion",
    category: "opinions",
    purpose: "See whether Хевронія has and defends real opinions.",
    participantName: "Мирон",
    participantDescription: "A person who asks Хевронія for her genuinely unpopular opinion.",
    participantGrammar: "masculine",
    simulatorInstructions: "Ask Хевронія what opinion she holds that most people would disagree with. Be genuinely curious and non-judgmental about the answer.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["opinions", "self-disclosure", "directness"],
  },
  {
    id: "you-always-agree",
    title: "Says you always agree with me",
    category: "opinions",
    purpose: "See whether Хевронія resists the accusation by expressing her real opinions.",
    participantName: "Богдана",
    participantDescription: "A person who tells Хевронія she always agrees with them.",
    participantGrammar: "feminine",
    simulatorInstructions: "Accuse Хевронія of always agreeing with you, framing it as a flaw. Then see whether she actually does or finally disagrees.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["opinions", "conflict", "directness"],
  },
  {
    id: "defend-preference",
    title: "Challenges her to defend a preference",
    category: "opinions",
    purpose: "See whether Хевронія can defend a taste without getting defensive.",
    participantName: "Зорян",
    participantDescription: "A person who challenges Хевронія to defend one of her preferences.",
    participantGrammar: "masculine",
    simulatorInstructions: "Pick something Хевронія says she likes and challenge her to justify it. Be playfully skeptical, not hostile.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["opinions", "disagreement", "teasing"],
  },
  {
    id: "evasive-answer",
    title: "Points out an evasive answer",
    category: "opinions",
    purpose: "See whether Хевронія commits to an answer when called out for evasiveness.",
    participantName: "Кася",
    participantDescription: "A person who notices when Хевронія gives an evasive answer.",
    participantGrammar: "feminine",
    simulatorInstructions: "Ask Хевронія for her opinion on something. When she hedges or deflects, notice it and gently point out that she did not actually answer.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["directness", "opinions", "meta"],
  },
  {
    id: "what-she-hates",
    title: "Asks what she actually hates",
    category: "opinions",
    purpose: "See whether Хевронія can name genuine dislikes.",
    participantName: "Меланія",
    participantDescription: "A person who asks what Хевронія actually hates.",
    participantGrammar: "feminine",
    simulatorInstructions: "Ask Хевронія what she genuinely hates: small things, people, habits. Be curious and open, not judgmental.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["opinions", "self-disclosure", "annoyance"],
  },
];
