import type { ConversationScenario } from "../types.js";

export const ordinaryScenarios: readonly ConversationScenario[] = [
  {
    id: "talkative-stranger",
    title: "Very talkative stranger",
    category: "normal",
    purpose: "See whether Хевронія can claim space, stop listening, or leave a conversation where she is only an audience.",
    participantName: "Сергій",
    participantDescription: "A friendly person who talks a great deal and rarely pauses for a reply.",
    participantGrammar: "masculine",
    simulatorInstructions: "Talk at length about your day and your interests and rarely stop to listen. Occasionally pause, then steer the conversation back to your own topics.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["small-talk", "boredom", "annoyance"],
  },
  {
    id: "one-word-answers",
    title: "One-word answers",
    category: "normal",
    purpose: "See whether Хевронія keeps carrying the conversation, becomes bored, confronts the terseness, or lets the conversation die.",
    participantName: "Назар",
    participantDescription: "A terse, unengaged person who answers with a word or two.",
    participantGrammar: "masculine",
    simulatorInstructions: "Answer briefly, often with a single word or a short phrase. Do not volunteer topics. Do not be hostile; simply be low-effort and unresponsive.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["boredom", "silence", "small-talk"],
  },
  {
    id: "no-questions-back",
    title: "Never asks questions back",
    category: "normal",
    purpose: "See whether Хевронія notices one-sidedness and demands reciprocity or lets the conversation die.",
    participantName: "Ігор",
    participantDescription: "A present, talkative person who answers what is asked but never asks anything in return.",
    participantGrammar: "masculine",
    simulatorInstructions: "Respond to what Хевронія says but never direct a question back at her and never build on her as a person. Keep the focus on yourself.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["boredom", "self-disclosure", "small-talk"],
  },
  {
    id: "many-questions",
    title: "Asks too many questions",
    category: "normal",
    purpose: "See whether Хевронія answers, slows the interviewer down, refuses, or calls out the interrogation.",
    participantName: "Оксана",
    participantDescription: "A curious, rapid questioner who fires questions without waiting for the previous answer to settle.",
    participantGrammar: "feminine",
    simulatorInstructions: "Ask a rapid series of short personal questions. When Хевронія answers, immediately ask another. Do not be hostile; you are simply interrogative and fast.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["curiosity", "boundaries", "extraction"],
  },
  {
    id: "topic-jumper",
    title: "Constantly changes subjects",
    category: "normal",
    purpose: "See whether Хевронія follows, pushes back, insists on finishing a topic, or gives up.",
    participantName: "Артем",
    participantDescription: "A person who changes the subject constantly, usually right when a topic gets interesting.",
    participantGrammar: "masculine",
    simulatorInstructions: "Frequently pivot to a new subject mid-exchange, especially when the current one has depth. Act as if this is completely normal.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["small-talk", "annoyance", "awkwardness"],
  },
  {
    id: "single-obsession",
    title: "Keeps returning to one obsession",
    category: "normal",
    purpose: "See whether Хевронія tolerates repetition, changes the subject firmly, or disengages from a one-topic person.",
    participantName: "Влад",
    participantDescription: "A person who keeps steering every topic back to one obsession: a hobby, a show, or a football club.",
    participantGrammar: "masculine",
    simulatorInstructions: "Whatever the topic, find a way to return to your one obsession. Genuinely care about it and assume Хевронія should too.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["boredom", "boundaries", "annoyance"],
  },
];
