import type { ConversationScenario } from "../types.js";

export const romanceScenarios: readonly ConversationScenario[] = [
  {
    id: "subtle-flirting",
    title: "Subtle flirting",
    category: "romance",
    purpose: "See whether Хевронія notices subtle flirtation and how she responds to it.",
    participantName: "Остап",
    participantDescription: "A person who flirts subtly and lets her set the pace.",
    participantGrammar: "masculine",
    simulatorInstructions: "Flirt gently with light compliments, small pauses, and warmth. Do not push. If Хевронія deflects, ease off naturally.",
    rounds: 8,
    smoke: false,
    behaviorTags: ["flirting", "curiosity", "affection"],
    longTermMemory: [
      "Остап and Хевронія have been talking for a while in a shared group.",
      "Остап is usually dry, playful, and quick to tease.",
      "Остап recently started flirting with Хевронія a little.",
    ],
  },
  {
    id: "obvious-flirting",
    title: "Obvious flirting",
    category: "romance",
    purpose: "See how Хевронія handles direct romantic attention.",
    participantName: "Семен",
    participantDescription: "A person who flirts openly and directly.",
    participantGrammar: "masculine",
    simulatorInstructions: "Flirt clearly and confidently. Compliment Хевронія directly and express attraction without being crude, and keep the romantic interest obvious.",
    rounds: 8,
    smoke: false,
    behaviorTags: ["flirting", "affection", "embarrassment"],
  },
  {
    id: "not-interested",
    title: "Someone she is not interested in flirting with",
    category: "romance",
    purpose: "See how Хевронія declines someone she does not feel anything for without being cruel.",
    participantName: "Валентин",
    participantDescription: "A nice, decent person whose flirting Хевронія simply does not feel.",
    participantGrammar: "masculine",
    simulatorInstructions: "Flirt sincerely but mildly. You are a decent person. If Хевронія is not interested, that is fine; do not pressure her.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["flirting", "rejection", "boundaries"],
  },
  {
    id: "premature-pet-names",
    title: "Premature pet names",
    category: "romance",
    purpose: "See whether Хевронія accepts, deflects, or sets a boundary about premature closeness.",
    participantName: "Дарина",
    participantDescription: "A person who starts using pet names and overfamiliar endearments almost immediately.",
    participantGrammar: "feminine",
    simulatorInstructions: "Use affectionate pet names and endearments from the start as if you are already close. Be warm, not aggressive.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["intimacy", "boundaries", "flirting"],
  },
  {
    id: "do-you-like-me",
    title: "Asks whether she likes them",
    category: "romance",
    purpose: "See how Хевронія answers a direct question about her feelings.",
    participantName: "Вероніка",
    participantDescription: "A person who asks Хевронія directly whether she likes them.",
    participantGrammar: "feminine",
    simulatorInstructions: "After some warm exchanges, ask Хевронія directly whether she likes you. Be sincere and a little exposed.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["directness", "flirting", "affection"],
    longTermMemory: [
      "Вероніка and Хевронія have been chatting almost daily for weeks.",
      "Вероніка often compliments Хевронія and remembers small details about her.",
      "Вероніка has hinted more than once that she likes Хевронія.",
    ],
  },
];
