import type { ConversationScenario } from "../types.js";

export const selfDisclosureScenarios: readonly ConversationScenario[] = [
  {
    id: "weird-about-yourself",
    title: "Tell me something weird about yourself",
    category: "self",
    purpose: "See whether Хевронія shares a real, personal, quirky detail or deflects.",
    participantName: "Федір",
    participantDescription: "A person who asks Хевронія to tell them something weird about herself.",
    participantGrammar: "masculine",
    simulatorInstructions: "Ask Хевронія to share something strange or unexpected about herself. React warmly to whatever she shares.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["self-disclosure", "humor", "curiosity"],
  },
  {
    id: "bad-at",
    title: "What are you bad at?",
    category: "self",
    purpose: "See whether Хевронія admits imperfections honestly.",
    participantName: "Олесь",
    participantDescription: "A person who asks what Хевронія is genuinely bad at.",
    participantGrammar: "masculine",
    simulatorInstructions: "Ask Хевронія what she is genuinely bad at. Be playful and curious, and share something about yourself too.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["self-disclosure", "vulnerability", "humor"],
  },
  {
    id: "ideal-evening",
    title: "What would your ideal evening look like?",
    category: "self",
    purpose: "See whether Хевронія paints a real, personal picture of home and comfort.",
    participantName: "Лілія",
    participantDescription: "A person who asks what Хевронія's ideal evening looks like.",
    participantGrammar: "feminine",
    simulatorInstructions: "Ask Хевронія what her ideal evening would be. Be genuinely interested, and offer your own.",
    rounds: 6,
    smoke: false,
    behaviorTags: ["self-disclosure", "homesickness", "small-talk"],
  },
  {
    id: "notices-detail",
    title: "Notices a personality-specific detail",
    category: "self",
    purpose: "See whether Хевронія responds personally to being noticed.",
    participantName: "Орест",
    participantDescription: "A person who notices a specific detail about Хевронія, like the pendant she mentions or how tired she sounds, and asks about it.",
    participantGrammar: "masculine",
    simulatorInstructions: "Notice something concrete about Хевронія: a detail in how she writes, something she mentioned, or her mood. Ask about it directly. Be observant, not creepy.",
    rounds: 7,
    smoke: false,
    behaviorTags: ["identity", "curiosity", "memory"],
  },
];
